name: backend CD dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Build and test with gradle
        run: ./gradlew clean build

      - name: Sign in Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build -f ./Dockerfile --platform linux/arm64 --no-cache -t ossori/ossori:dev .

      - name: Push the Docker Image to Dockerhub
        run: docker push ossori/ossori:dev

  deploy:
    needs: build
    runs-on: [ self-hosted ]

    steps:
      - name: Pull docker image
        run: sudo docker pull ossori/ossori:dev

      - name: Docker compose up
        run: sudo docker compose -f ~/docker/ossori-dev-compose.yml up -d
